version: '2.2'
services:
  registrotarefas:
    container_name: registrodetarefas
    image: registrodetarefas
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
